# Generated by Django 5.2.7 on 2026-04-01 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='mentor',
        ),
        migrations.RemoveField(
            model_name='course',
            name='teachers',
        ),
    ]
