# Generated by Django 5.2.14 on 2026-05-31 20:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes_app', '0005_scheduling_and_cancellation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='hourly_rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Payment rate per hour (₹)', max_digits=8),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='MentorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_approved', models.BooleanField(default=False)),
                ('hourly_rate', models.DecimalField(decimal_places=2, default=0, help_text='Payment rate per hour (₹)', max_digits=8)),
                ('user', models.OneToOneField(limit_choices_to={'role': 'mentor'}, on_delete=django.db.models.deletion.CASCADE, related_name='classes_mentor_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
