# Generated by Django 5.2.14 on 2026-06-01 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes_app', '0006_teacherprofile_hourly_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classsession',
            name='demo_outcome',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
    ]
