# Generated by Django 5.2.14 on 2026-07-24 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes_app', '0009_alter_teacherprofile_hourly_rate_supportticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='profile_picture_base64',
            field=models.TextField(blank=True, help_text='Base64 encoded WebP image', null=True),
        ),
        migrations.DeleteModel(
            name='SupportTicket',
        ),
    ]
