# Generated by Django 5.2.7 on 2026-09-16 10:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes_app', '0012_booking_razorpay_order_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='classsession',
            name='meet_link_added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_meet_links', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='classsession',
            name='meet_link_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='classsession',
            name='outcome_marked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='classsession',
            name='outcome_marked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marked_session_outcomes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='classsession',
            name='outcome_remarks',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='bookingschedule',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('live', 'Live / Active'), ('completed', 'Completed'), ('not_conducted', 'Not Conducted'), ('cancelled', 'Cancelled'), ('needs_review', 'Expired / Needs Review')], default='scheduled', max_length=20),
        ),
        migrations.AlterField(
            model_name='classsession',
            name='status',
            field=models.CharField(choices=[('Scheduled', 'Scheduled'), ('Live', 'Live / Active'), ('Completed', 'Completed'), ('Not Conducted', 'Not Conducted'), ('Cancelled', 'Cancelled'), ('Needs Review', 'Expired / Needs Review')], default='Scheduled', max_length=20),
        ),
        migrations.CreateModel(
            name='ClassReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('individual', 'Individual Student'), ('cohort', 'Class Cohort')], default='individual', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('reviewed', 'Reviewed'), ('approved', 'Approved')], default='submitted', max_length=20)),
                ('performance_rating', models.PositiveSmallIntegerField(default=5, help_text='Rating out of 10')),
                ('attendance_observation', models.CharField(blank=True, default='Present', max_length=100)),
                ('homework_completion', models.CharField(choices=[('completed', 'Completed'), ('partial', 'Partially Completed'), ('not_done', 'Not Completed'), ('not_assigned', 'Not Assigned')], default='completed', max_length=30)),
                ('strengths', models.TextField(blank=True, default='')),
                ('areas_for_improvement', models.TextField(blank=True, default='')),
                ('recommendations', models.TextField(blank=True, default='')),
                ('text_report', models.TextField(blank=True, default='')),
                ('pdf_report', models.FileField(blank=True, null=True, upload_to='reports/pdf/')),
                ('voice_note', models.FileField(blank=True, null=True, upload_to='reports/audio/')),
                ('voice_note_duration', models.IntegerField(blank=True, help_text='Duration in seconds', null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='classes_app.classsession')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_reports', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(blank=True, limit_choices_to={'role': 'student'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_reports', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='submitted_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DailyClassVoiceNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('audio_file', models.FileField(upload_to='voice_notes/')),
                ('text_summary', models.TextField(blank=True, default='')),
                ('duration_seconds', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted')], default='submitted', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('class_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voice_notes', to='classes_app.classsession')),
                ('student', models.ForeignKey(blank=True, limit_choices_to={'role': 'student'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_voice_notes', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='daily_voice_notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TeacherMonthlyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveSmallIntegerField(help_text='Month number 1-12')),
                ('year', models.PositiveSmallIntegerField(help_text='e.g. 2026')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('reviewed', 'Reviewed'), ('approved', 'Approved')], default='submitted', max_length=20)),
                ('classes_conducted_count', models.PositiveIntegerField(default=0)),
                ('classes_not_conducted_count', models.PositiveIntegerField(default=0)),
                ('total_teaching_hours', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
                ('attendance_summary', models.JSONField(blank=True, default=dict, help_text='Summary breakdown of attendance')),
                ('student_progress_notes', models.TextField(blank=True, default='')),
                ('tasks_assigned_completed', models.TextField(blank=True, default='')),
                ('important_observations', models.TextField(blank=True, default='')),
                ('voice_notes_count', models.PositiveIntegerField(default=0)),
                ('overall_remarks', models.TextField(blank=True, default='')),
                ('next_month_recommendations', models.TextField(blank=True, default='')),
                ('pdf_report_file', models.FileField(blank=True, null=True, upload_to='monthly_reports/pdf/')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_monthly_reports', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='monthly_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-year', '-month'],
                'unique_together': {('teacher', 'year', 'month')},
            },
        ),
    ]
