# Generated by Django 5.2.7 on 2026-10-08 17:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes_app', '0013_classsession_meet_link_added_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='expires_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Reservation timeout for pending bookings (15 min)', null=True),
        ),
        migrations.AddConstraint(
            model_name='classsession',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'Cancelled'), _negated=True), fields=('teacher', 'scheduled_time'), name='unique_active_teacher_scheduled_time'),
        ),
    ]
