# Generated by Django 5.2.7 on 2026-10-08 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes_app', '0014_booking_expires_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyclassvoicenote',
            name='class_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='voice_notes', to='classes_app.classsession'),
        ),
    ]
