# Generated by Django 5.2.7 on 2026-03-08 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='interviewed',
            field=models.BooleanField(default=False),
        ),
    ]
