# Generated by Django 5.2.7 on 2026-04-24 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0002_jobapplication_interviewed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='portfolio',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
