# Generated by Django 5.2.14 on 2026-06-01 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0004_jobapplication_academy_details_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='portfolio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
