# Generated by Django 5.2.7 on 2025-12-08 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.CharField(choices=[('General Aptitude', 'General Aptitude'), ('Engineering Mathematics', 'Engineering Mathematics'), ('Subject Paper', 'Subject Paper')], default='Subject Paper', max_length=50),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
