# Generated by Django 4.2.27 on 2026-01-08 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_complaint'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='resolution_comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
