# Generated by Django 5.2.7 on 2026-01-14 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_contactinquiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinquiry',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Resolved', 'Resolved')], default='Pending', max_length=20),
        ),
    ]
