# Generated by Django 5.2.7 on 2026-03-28 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_user_platform_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinquiry',
            name='platform',
            field=models.CharField(choices=[('gate', 'GATE'), ('classes', 'Classes')], default='gate', max_length=10),
        ),
    ]
