# Generated by Django 5.2.7 on 2026-05-09 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_staffprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinquiry',
            name='resolution_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contactinquiry',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
