# Generated by Django 5.2.14 on 2026-05-31 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_contactinquiry_resolution_comment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='assigned_teacher',
        ),
    ]
