# Generated by Django 5.2.7 on 2026-09-10 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_remove_assigned_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account_status',
            field=models.CharField(choices=[('active', 'Active'), ('hold', 'On Hold'), ('banned', 'Banned')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='status_reason',
            field=models.TextField(blank=True, default=''),
        ),
    ]
