# Generated by Django 5.2.7 on 2026-09-16 10:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_user_account_status_user_status_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='stafftask',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stafftask',
            name='payment_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stafftask',
            name='payment_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_task_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stafftask',
            name='payment_assigned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stafftask',
            name='payment_assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_task_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stafftask',
            name='payment_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stafftask',
            name='payment_status',
            field=models.CharField(choices=[('not_assigned', 'Not Yet Assigned'), ('awaiting_review', 'Awaiting Review'), ('amount_assigned', 'Amount Assigned'), ('approved', 'Approved'), ('paid', 'Paid'), ('on_hold', 'On Hold'), ('disputed', 'Disputed')], default='not_assigned', max_length=30),
        ),
        migrations.AddField(
            model_name='stafftask',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stafftask',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stafftask',
            name='reviewer_feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stafftask',
            name='revision_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stafftask',
            name='submission_file',
            field=models.FileField(blank=True, null=True, upload_to='task_submissions/'),
        ),
        migrations.AddField(
            model_name='stafftask',
            name='submission_image',
            field=models.FileField(blank=True, null=True, upload_to='task_submissions/images/'),
        ),
        migrations.AddField(
            model_name='stafftask',
            name='submission_report',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stafftask',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stafftask',
            name='time_spent_hours',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='stafftask',
            name='status',
            field=models.CharField(choices=[('assigned', 'Assigned'), ('pending', 'Assigned'), ('in_progress', 'In Progress'), ('submitted_for_review', 'Submitted for Review'), ('approved', 'Approved'), ('revision_required', 'Revision Required'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='assigned', max_length=30),
        ),
        migrations.CreateModel(
            name='TaskPaymentAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('new_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('old_status', models.CharField(max_length=30)),
                ('new_status', models.CharField(max_length=30)),
                ('reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_audit_logs', to='api.stafftask')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskSubmissionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_report', models.TextField(blank=True, null=True)),
                ('submission_file', models.FileField(blank=True, null=True, upload_to='task_submissions/')),
                ('submission_image', models.FileField(blank=True, null=True, upload_to='task_submissions/images/')),
                ('time_spent_hours', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewer_feedback', models.TextField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_task_submissions', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_submissions', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submission_history', to='api.stafftask')),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
    ]
