# Generated by Django 5.2.7 on 2026-09-16 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_stafftask_paid_at_stafftask_payment_approved_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='assigned_modules',
            field=models.JSONField(blank=True, default=list, help_text='Individual staff module permissions'),
        ),
    ]
