# Generated by Django 5.2.7 on 2026-04-13 12:40

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0010_alter_user_role_staffprofile_stafftask_taskcomment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
            ],
            options={
                'verbose_name': 'Complaint',
                'verbose_name_plural': 'Complaints',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('api.complaint',),
        ),
        migrations.CreateModel(
            name='ContactInquiry',
            fields=[
            ],
            options={
                'verbose_name': 'Contact Inquiry',
                'verbose_name_plural': 'Contact Inquiries',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('api.contactinquiry',),
        ),
    ]
