# Generated by Django 5.2.7 on 2026-04-13 12:40

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0010_alter_user_role_staffprofile_stafftask_taskcomment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
            ],
            options={
                'verbose_name': 'Choice',
                'verbose_name_plural': 'Choices',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('api.choice',),
        ),
        migrations.CreateModel(
            name='CourseRequest',
            fields=[
            ],
            options={
                'verbose_name': 'Course Request',
                'verbose_name_plural': 'Course Requests',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('api.courserequest',),
        ),
        migrations.CreateModel(
            name='MockTest',
            fields=[
            ],
            options={
                'verbose_name': 'Mock Test',
                'verbose_name_plural': 'Mock Tests',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('api.mocktest',),
        ),
        migrations.CreateModel(
            name='MockTestQuestion',
            fields=[
            ],
            options={
                'verbose_name': 'Mock Test Question',
                'verbose_name_plural': 'Mock Test Questions',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('api.mocktestquestion',),
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('api.question',),
        ),
        migrations.CreateModel(
            name='StudyMaterial',
            fields=[
            ],
            options={
                'verbose_name': 'Study Material',
                'verbose_name_plural': 'Study Materials',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('api.studymaterial',),
        ),
    ]
