# Generated by Django 5.2.7 on 2026-04-13 12:40

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0010_alter_user_role_staffprofile_stafftask_taskcomment'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
            ],
            options={
                'verbose_name': 'Staff Profile',
                'verbose_name_plural': 'Staff Profiles',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('api.staffprofile',),
        ),
        migrations.CreateModel(
            name='StaffTask',
            fields=[
            ],
            options={
                'verbose_name': 'Staff Task',
                'verbose_name_plural': 'Staff Tasks',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('api.stafftask',),
        ),
        migrations.CreateModel(
            name='TaskComment',
            fields=[
            ],
            options={
                'verbose_name': 'Task Comment',
                'verbose_name_plural': 'Task Comments',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('api.taskcomment',),
        ),
    ]
