from django.db import models
from django.contrib.auth.models import AbstractUser
from django.conf import settings

# --- CORE MODELS ---

class Branch(models.Model):
    name = models.CharField(max_length=100)
    
    def __str__(self): 
        return self.name

class User(AbstractUser):
    ROLE_CHOICES = (('student', 'Student'), ('admin', 'Admin'))
    
    email = models.EmailField(unique=True)
    role = models.CharField(max_length=10, choices=ROLE_CHOICES, default='student')
    student_id = models.CharField(max_length=20, unique=True, null=True, blank=True)
    branch = models.ForeignKey(Branch, on_delete=models.SET_NULL, null=True, blank=True)
    
    # Extra Profile Fields
    college = models.CharField(max_length=200, blank=True, null=True)
    phone_number = models.CharField(max_length=15, blank=True, null=True)

    # Verification & OTP
    is_verified = models.BooleanField(default=False)
    otp = models.CharField(max_length=6, blank=True, null=True) 
    otp_expiry = models.DateTimeField(blank=True, null=True)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username']

    def __str__(self):
        return self.email

# --- COURSE & MATERIAL MODELS ---

class StudyMaterial(models.Model):
    CLASSIFICATION_CHOICES = (('PYQ', 'PYQ'), ('Notes', 'Notes'), ('One-shots', 'One-shots'))
    
    title = models.CharField(max_length=200)
    file = models.FileField(upload_to='materials/')
    classification = models.CharField(max_length=10, choices=CLASSIFICATION_CHOICES)
    branch = models.ForeignKey(Branch, on_delete=models.CASCADE)
    is_preview = models.BooleanField(default=False)

    def __str__(self): 
        return self.title

class CourseRequest(models.Model):
    STATUS_CHOICES = (('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'))
    
    student = models.ForeignKey(User, on_delete=models.CASCADE)
    branch = models.ForeignKey(Branch, on_delete=models.CASCADE)
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='Pending')

    def __str__(self): 
        return f"{self.student.username} - {self.branch.name} ({self.status})"

# --- SECURITY MODELS ---

class Session(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    session_key = models.TextField(primary_key=True) 
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.user.username}'s active session"

# --- QUESTION BANK & MOCK TEST MODELS ---

class Category(models.Model):
    """Categories for questions, e.g., 'Aptitude', 'Data Structures', 'Thermodynamics'"""
    name = models.CharField(max_length=100)
    description = models.TextField(blank=True, null=True)

    def __str__(self):
        return self.name

class Question(models.Model):
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True, related_name='questions')
    text = models.TextField()
    marks = models.IntegerField(default=1)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self): 
        return str(self.text)[:50]

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE, related_name='choices')
    text = models.CharField(max_length=200)
    is_correct = models.BooleanField(default=False)

    def __str__(self): 
        return self.text

class MockTest(models.Model):
    """Represents a specific test session generated by a student"""
    student = models.ForeignKey(User, on_delete=models.CASCADE, related_name='mock_tests')
    created_at = models.DateTimeField(auto_now_add=True)
    completed_at = models.DateTimeField(null=True, blank=True)
    
    # Test Configuration snapshot
    total_questions = models.IntegerField()
    time_limit_minutes = models.IntegerField()
    
    # Result
    score = models.FloatField(default=0.0)
    is_completed = models.BooleanField(default=False)

    def __str__(self): 
        return f"Test {self.id} - {self.student.username}"

class MockTestQuestion(models.Model):
    """Link table to store the state of each question in a specific test"""
    mock_test = models.ForeignKey(MockTest, on_delete=models.CASCADE, related_name='test_questions')
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    
    # Store user's answer
    selected_choice = models.ForeignKey(Choice, on_delete=models.SET_NULL, null=True, blank=True)
    is_correct = models.BooleanField(default=False)
    
    # To preserve order or help with analytics
    order = models.PositiveIntegerField(default=0)

    class Meta:
        unique_together = ('mock_test', 'question')